- hosts: labservers
  become: yes
  tasks:
  - name: remove firewalld package
    yum:
      name: firewalld
      state: absent
  - name: remove apache
    yum:
      name: httpd
      state: absent

