---
# handlers file for roles/app-tier
- name: retart_httpd
  service:
   name: "{{ httpd_srv }}"
   state: restarted
 EOF
 
cd ansible

cat << EOF > roles/app-tier/vars/main.yml
---
# vars file for roles/app-tier
db:
 user: root
 database: userdb
 password: redhat
httpd_pkg:
 - httpd
 - php
 - php-mysql
httpd_srv: httpd
db_srv: mariadb
